server:
  http:
    listen_address: "0.0.0.0"
    listen_port: 9080

receivers:
  filelog:
    n8n:
      include:
        - /var/log/n8n/*.log
      start_at: end
      positions_file: /var/lib/alloy/positions.yml
      labels:
        job: n8n-logs

exporters:
  loki:
    default:
      endpoint: http://loki:3100/loki/api/v1/push

service:
  pipelines:
    logs:
      receivers: [n8n]
      exporters: [default]